name: Build addon archive
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install gitman
        run: pipx install gitman
      - name: install dependencies
        run: gitman install
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "{VERSION}"
          include: LedgerChat.toc
          replace: "${{ env.RELEASE_VERSION }}"
      - run: mkdir LedgerChat
      - run: mv !(LedgerChat) LedgerChat
      - run: zip -r LedgerChat.zip LedgerChat
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          #prerelease_regex: "^v0\\.[[:digit:]]+\\.[[:digit:]]+"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact to github
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: LedgerChat.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to curseforge
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 457157
          game_endpoint: wow
          file_path: LedgerChat.zip
          changelog: See github for changes
          display_name: LedgerChat
          game_versions: 1-13-4
          release_type: alpha
          #relations:
